### ISSUE TITLE
Pagination selector classnames instead of tagname

### ISSUE THREAD

**Issue by larsvanpoucke** [a-ui/core_branding_scss#112]
Can you add a .m-pagination__button or .m-pagination__page class that contains the styling of the child elements of the pagination molecule?

https://github.com/a-ui/core_branding_scss/blob/master/src/styles/molecules/_molecules.pagination.scss

Should be something like this:
```html
<ul class="m-pagination">
  <li class="m-pagination__button">1</li>
  <li class="m-pagination__button">2</li>
  <li class="m-pagination__button">3</li>
  <li class="m-pagination__button m-pagination__button--disabled">...</li>
</ul>
```

Now the styling is applied to a specific dom element (li-tag) which is not very reusable / flexible.

Styling selectors should be classnames instead of `<a>-tag`.
That way we can also use stuff like `<button>` as a pagination-element.

**Comment by TriangleJuice** [comment]
For accessibility reasons (WCAG 2.1 AA) we don't support buttons within our pagination component. There shouldn't be any limits in using links instead of buttons.
