### ISSUE TITLE
Toggle button shows half of both labels if active

### ISSUE THREAD

**Issue by vivalaik** [a-ui/core_branding_scss#127]
When using the toggle from the styleguide, half of both labels is viable when it becomes active.

```
<div class="a-toggle">
    <input class="a-toggle__checkbox" id="toggle-normal" type="checkbox">
    <div class="a-toggle__labels">
        <label for="toggle-normal" class="a-toggle__on a-button has-icon-left">
            <i class="fa fa-bars"></i>
            Open
        </label>
        <label for="toggle-normal" class="a-toggle__off a-button a-button--danger has-icon-left">
            <i class="fa fa-close"></i>
            Close
        </label>
    </div>
</div>
```
![image](https://user-images.githubusercontent.com/25488332/55797886-daf81e00-5acd-11e9-9626-5afd1417c341.png)

EDIT 1:
When using it in another place it works fine. I tried changing the id's, but the behavouir stayed the same.

**Comment by TriangleJuice** [comment]
How can we reproduce the bug? Which browsers are affected? Is there any chance that there are any styling declarations in your project that overwrite ours?

**Comment by vivalaik** [comment]
- To reproduce the bug, user the code provided
- There shouldn't be any styling overwriting styles because on an other place in the website it works fine.

**Comment by TriangleJuice** [comment]
If I use the code provided, I get the expected output. See this codepen: https://codepen.io/TriangleJuice/pen/wZEzYR

You are always welcome to drop by at Digipolis, so we can help you looking into this issue.
