### ISSUE TITLE
Images of Avatars not loading

### ISSUE THREAD

**Issue by Veyfeyken** [a-ui/core_branding_scss#144]
[atoms/atoms.avatar](https://a-ui.github.io/core_branding_scss/#atoms-avatar)

![20201104-13-30-39](https://user-images.githubusercontent.com/870049/98112130-f2fa7400-1ea1-11eb-86cb-d7cd8bb46f3d.jpg)

**Comment by TriangleJuice** [comment]
Fixed in #178
