### ISSUE TITLE
Use a button instead of a checkbox for the toggle component

### ISSUE THREAD

**Issue by Veyfeyken** [a-ui/core_branding_scss#150]
### Problem

[atoms/atoms.toggle](https://a-ui.github.io/core_branding_scss/#atoms-toggle)

This is related to the problem as described in the issue [Use a button instead of a checkbox for the switch component #149](https://github.com/a-ui/core_branding_scss/issues/149). A checkbox is not suited for opening a menu.

```html
<div class="a-toggle has-icon">
  <input class="a-toggle__checkbox" id="icon-toggle" type="checkbox" role="switch" aria-checked="false">
  <div class="a-toggle__labels">
    <label for="icon-toggle" class="a-toggle__on a-button has-icon">
      <span class="fa fa-bars"><span class="u-screen-reader-only">Open menu</span></span>
    </label>
    <label for="icon-toggle" class="a-toggle__off a-button a-button--danger has-icon">
      <span class="fa fa-close"><span class="u-screen-reader-only">Close menu</span></span>
    </label>
  </div>
</div>
```

![20201109-14-04-41](https://user-images.githubusercontent.com/870049/98544665-9b3e7d00-2294-11eb-9a68-89257f86381c.jpg)
![20201109-14-05-33](https://user-images.githubusercontent.com/870049/98544696-a5f91200-2294-11eb-8421-c991f9222f88.jpg)

### Solution

Implement it as a show-hide component as explained in the ARIA design pattern:

* Use a button instead of a checkbox.
* Add an aria-expanded="true/false" attribute to the button.
* Use "menu" as the button's text (visually hidden if necessary).
* Delete the label elements.
* Delete the role="switch" and the aria-checked attribute. The aria-expanded attribute announces the state.

### Links and articles
* [ARIA Design pattern and widgets: Disclosure (Show/Hide)](https://www.w3.org/TR/wai-aria-practices-1.2/#disclosure)
* [Accessible Rich Internet Applications (WAI-ARIA) 1.2: aria-expanded (state)](https://www.w3.org/TR/wai-aria-1.2/#aria-expanded)

**Comment by TriangleJuice** [comment]
Fixed in #183
