### ISSUE TITLE
Change the alt-text of the logo that links to the homepage in the header component

### ISSUE THREAD

**Issue by Veyfeyken** [a-ui/core_branding_scss#163]
### Problem

[organisms/organisms.header](https://a-ui.github.io/core_branding_scss/#organisms-header)

The link with the logo in the header doesn't say where the link goes. alt="Official logo Antwerpen" is not a good alt-text in this context. 

```html
<a href="#" class="o-header__logo">
 <img src="images/a-logo.svg" alt="Official logo Antwerpen">
</a>
```

### Solution

Change the alt-text to alt="homepage Antwerp" or something similar.

### Links and articles

[Understanding Success Criterion 1.1.1: Non-text Content](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html)

**Comment by TriangleJuice** [comment]
Fixed in #178
