### ISSUE TITLE
Use a button for the menu button instead of a link in the header component

### ISSUE THREAD

**Issue by Veyfeyken** [a-ui/core_branding_scss#164]
### Problem

[organisms/organisms.header](https://a-ui.github.io/core_branding_scss/#organisms-header)

Use buttons for actions and links for navigating to other pages. The menu button will open a menu? This is an action, therefore a button would be semantically more appropriate. Buttons and link create different expectations and behave differently.

```html
<a href="#" class="a-button-negative o-header__button">Menu button</a>
```

![screenshot header](https://user-images.githubusercontent.com/870049/98692666-aa462d80-236f-11eb-9cc6-18e164b7684c.jpg)

### Solution

Use buttons for actions and links for navigation.

### Links and articles

[CSS Tricks: A Complete Guide to Links and Buttons](https://css-tricks.com/a-complete-guide-to-links-and-buttons/)

**Comment by TriangleJuice** [comment]
Fixed in #183
