### ISSUE TITLE
Don't hide the label element of the tag input

### ISSUE THREAD

**Issue by Veyfeyken** [a-ui/core_branding_scss#173]
[molecules/molecules.tag](https://a-ui.github.io/core_branding_scss/#molecules-tag)

The following recommendation is an accessibility improvement but not required to achieve WCAG compliance.

Don't hide the label element. It's useful for everybody because the placeholder attribute is hard to read. It scores low on contrast. That's an exception in WCAG because the colors are set by the user agent (browser). The placeholder also disappears when the field has focus.

```html
<div class="m-tag">
  <label for="new-tag" class="u-screen-reader-only">Insert new tag</label>
  <input id="new-tag" class="m-tag__input" type="text" placeholder="Insert new tag" />
</div>
```

![20201116-15-18-29](https://user-images.githubusercontent.com/870049/99263058-ff29ee00-281e-11eb-87a1-8fbf2323ea83.jpg)

### Links and articles

[Nielsen Norman Group: Placeholders in Form Fields Are Harmful](http://www.nngroup.com/articles/form-design-placeholders/)

**Comment by TriangleJuice** [comment]
This functionality was removed from core branding v6
