### ISSUE TITLE
Consider translating all examples to Dutch

### ISSUE THREAD

**Issue by Veyfeyken** [a-ui/core_branding_scss#174]
All microcopy in the examples of the documentation has to be translated to Dutch considering the target audience. So it would be more efficient to write all examples (not the explanation) in Dutch? I'm afraid the alt-attributes, aria-labels, screenreader text will go live in the wrong language.

**Comment by TriangleJuice** [comment]
For budgetary reasons we won't change this behaviour. Also, if we would do this correctly, the Dutch translations would be accompanied by an appropriate lang attribute, which on its turn could also be copied into the code.

We hope to tackle these problems in interim reviews as well as in accessibility audits.
