### ISSUE TITLE
Consider hosting old versions

### ISSUE THREAD

**Issue by slckeknc** [a-ui/core_branding_scss#300]
We are still using version 5 but since v6 published we can't consult v5 documentation anymore.
It will be very helpful if it was still hosted somewhere.

**Comment by bbigda** [comment]
I also use version 5 in my project and to get docs for this version I use web.archive.org
Link to version 5 : [http://web.archive.org/web/20210620130440/https://a-ui.github.io/core_branding_scss/](url)

But this is not a good solution in the long term so I too wish there was other versions of documentation hosted.

**Comment by slckeknc** [comment]
Yes, indeed. I am currently running v5 branch in the repo locally in order to get acces to the docs.

**Comment by TriangleJuice** [comment]
Not hosting the old versions is budgetary decision. Plus, a good side effect is that older projects are encouraged to upgrade much sooner. Since older versions of core branding are also not fully WCAG 2.1 AA compliant, this is a good thing for accessibility too.
