### ISSUE TITLE
Aria-expanded attribuut van de accordion component staat niet op de button

### ISSUE THREAD

**Issue by Veyfeyken** [a-ui/core_branding_scss#302]
https://digitalehuisstijl.antwerpen.be/component/accordion

Het aria-expanded attribuut communiceert de staat van de accordion naar screenreaders (open of gesloten). Om te werken moet het op het element staan dat de accordion opent.

Verplaats het aria-expanded attribuut daarom van de parent `<div>` naar de `<button>` die de accordion opent. Anders heeft het geen effect.

```html
<div class="m-accordion__tab" aria-expanded="true">
      <button class="m-accordion__header">Aeneis</button>
```

Meer info:
https://www.w3.org/WAI/ARIA/apg/patterns/accordion/ 
https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/

**Comment by Veyfeyken** [comment]
Whoepsie, forgot these issues are supposed to be written in English.

**Comment by TriangleJuice** [comment]
`<div lang="nl">'t Is niets, Gijs. Bedankt voor het inseinen!</div>` 😉
