### ISSUE TITLE
The number of the steps is repeated multiple times by screenreaders

### ISSUE THREAD

**Issue by Veyfeyken** [a-ui/core_branding_scss#303]
https://digitalehuisstijl.antwerpen.be/component/step-indicator 

The steps are marked up as an `<ol>` but NVDA and VoiceOver don't announce the number. I assume because of the CSS list-style: none; on the `<li>`.

There is a number for each step and hidden text for screenreaders that repeat the step. Current output by NVDA screenreader: 

> lijst  met 5 items  1
> Step 1Location(completed)
> 2
> Step 2Introduction(completed)
> huidige stap  3
> Step 3Date and time
> 4
> Step 4Your credentials
> 5
> Step 5Checkout

Suggestion:
Only add "step" as hidden text and add it directly before the current number that is visually shown.

For example:

```html
<li class="is-completed">
 <span class="u-screen-reader-only">Step </span>
 <span class="m-step-indicator__number"></span>
 <span class="m-step-indicator__label">Location<span class="u-screen-reader-only"> (completed)</span></span>
</li>
```

**Comment by TriangleJuice** [comment]
Fixed in v6.1.0
