### ISSUE TITLE
npm package for version 6.1.0

### ISSUE THREAD

**Issue by bbigda** [a-ui/core_branding_scss#307]
Hey,

Once again it would be nice to have latest version of the package available via npm.

Maybe you could do some automation to upload new versions to npm as they are available ?

``` 
-> npm install @a-ui/core@6.1.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @a-ui/core@6.1.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by TriangleJuice** [comment]
Hey there. Sorry for the inconvenience! There was indeed a hiccup in our system. Should be resolved now.

**Comment by bbigda** [comment]
Great !

Thanks for the fast response. Im in the middle of migration form 5 -> 6 and I wanted to be up to date.
